// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuTevNMamciR5nKYSMaytTZOds9klQlss',
    appId: '1:291894791961:web:fee9935c3c0b70682d3f88',
    messagingSenderId: '291894791961',
    projectId: 'flutter-project-871cd',
    authDomain: 'flutter-project-871cd.firebaseapp.com',
    storageBucket: 'flutter-project-871cd.appspot.com',
    measurementId: 'G-8NNQY0BE5R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqLz3GKo_VE5u6u_c0LwXMYjreH3qmVC0',
    appId: '1:291894791961:android:2be04346deae99982d3f88',
    messagingSenderId: '291894791961',
    projectId: 'flutter-project-871cd',
    storageBucket: 'flutter-project-871cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI8OFHYaZIZtKyjUN5MMmeze2j_7wneS4',
    appId: '1:291894791961:ios:3380a2aac0e1cfa02d3f88',
    messagingSenderId: '291894791961',
    projectId: 'flutter-project-871cd',
    storageBucket: 'flutter-project-871cd.appspot.com',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI8OFHYaZIZtKyjUN5MMmeze2j_7wneS4',
    appId: '1:291894791961:ios:3380a2aac0e1cfa02d3f88',
    messagingSenderId: '291894791961',
    projectId: 'flutter-project-871cd',
    storageBucket: 'flutter-project-871cd.appspot.com',
    iosBundleId: 'com.example.demo',
  );
}
